### ISSUE TITLE
接入xxl-job的公司请留下 ”公司名称 + 公司官网地址“，谢谢。

### ISSUE THREAD

**Issue by xuxueli** [xuxueli/xxl-excel#1]

**Comment by PEAKWEI** [comment]
武汉生物工程学院 图书推荐系统 http://lib.whsw.cn/   开发中.................

**Comment by targerr** [comment]
Exception in thread "main" java.lang.IllegalStateException: Cannot get a STRING value from a NUMERIC cell
	at org.apache.poi.hssf.usermodel.HSSFCell.typeMismatch(HSSFCell.java:654)
	at org.apache.poi.hssf.usermodel.HSSFCell.getRichStringCellValue(HSSFCell.java:731)
	at org.apache.poi.hssf.usermodel.HSSFCell.getStringCellValue(HSSFCell.java:714)
	at com.xuxueli.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:70)
	at com.xuxueli.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:101)
	at com.xuxueli.poi.excel.ExcelImportUtil.importExcel(ExcelImportUtil.java:121)
	at com.xuxueli.poi.excel.test.JoinerTest.main(JoinerTest.java:32)

**Comment by zhuxiujia** [comment]
浙江华宜软件科技有限公司，http://www.duodianjinfu.com , 另外 提交了一项改进，望采纳~

**Comment by JaleelLiu** [comment]
广州知识圈网络科技有限公司  http://www.youyinian.cn
